FROM tomcat

MAINTAINER linux
#WORKDIR /usr/local/tomcat/webapps
COPY "/var/lib/jenkins/workspace/Samplemvnjob/target/WebApp.war" /usr/local/tomcat/webapps/WebApp.war
# RUN cd /usr/local/tomcat/webapps/

